# Generated by Django 5.2.7 on 2025-11-11 06:00

import xadmin_db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xadmin_db', '0002_testplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TpgenSavedPlan',
            fields=[
                ('id', models.BigAutoField(db_comment='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='测试计划名称', db_index=True, max_length=100)),
                ('category', models.CharField(db_comment='类别(Benchmark/Functional/Performance/Stress/Custom等)', db_index=True, max_length=50)),
                ('description', models.TextField(blank=True, db_comment='描述', null=True)),
                ('config_data', models.JSONField(db_comment='完整的测试计划配置数据（包含FormData）')),
                ('yaml_data', models.JSONField(blank=True, db_comment='生成的YAML数据结构', null=True)),
                ('cpu', models.CharField(blank=True, db_comment='CPU类型', max_length=100, null=True)),
                ('gpu', models.CharField(blank=True, db_comment='GPU类型', max_length=100, null=True)),
                ('machine_count', models.IntegerField(db_comment='选择的机器数量', default=0)),
                ('os_type', models.CharField(blank=True, db_comment='操作系统', max_length=50, null=True)),
                ('kernel_type', models.CharField(blank=True, db_comment='内核类型', max_length=50, null=True)),
                ('test_case_count', models.IntegerField(db_comment='测试用例数量', default=0)),
                ('status', models.PositiveIntegerField(db_comment='状态(1: 草稿; 2: 已发布; 3: 归档)', db_index=True, default=1)),
                ('tags', models.CharField(blank=True, db_comment='标签，逗号分隔', max_length=200, null=True)),
                ('use_count', models.IntegerField(db_comment='使用次数', default=0)),
                ('last_used_time', models.DateTimeField(blank=True, db_comment='最后使用时间', null=True)),
                ('create_user', models.BigIntegerField(db_comment='创建人ID', db_index=True)),
                ('create_user_name', models.CharField(blank=True, db_comment='创建人姓名', max_length=50, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_comment='创建时间', db_index=True)),
                ('update_user', models.BigIntegerField(blank=True, db_comment='修改人ID', null=True)),
                ('update_user_name', models.CharField(blank=True, db_comment='修改人姓名', max_length=50, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, db_comment='修改时间', null=True)),
            ],
            options={
                'db_table': 'tpgen_saved_plan',
                'db_table_comment': '测试计划配置保存表',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['name', 'category'], name='idx_name_category'), models.Index(fields=['create_user', 'category'], name='idx_user_category'), models.Index(fields=['-create_time'], name='idx_create_time_desc')],
            },
            bases=(xadmin_db.models.ModelSaveMixin, models.Model),
        ),
    ]
