# Generated by Django 5.2.7 on 2025-11-11 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xadmin_db', '0002_testplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestPlan',
        ),
    ]
