# Generated by Django 5.2.7 on 2025-11-12 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xadmin_db', '0003_delete_testplan'),
        ('xadmin_db', '0003_tpgensavedplan'),
    ]

    operations = [
    ]
