# Generated by Django 5.2.7 on 2025-11-12 03:06

import xadmin_db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('xadmin_db', '0004_merge_0003_delete_testplan_0003_tpgensavedplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.BigAutoField(db_comment='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='测试计划名称', max_length=100)),
                ('code', models.CharField(db_comment='测试计划编号', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, db_comment='描述', null=True)),
                ('start_time', models.DateTimeField(blank=True, db_comment='开始时间', null=True)),
                ('end_time', models.DateTimeField(blank=True, db_comment='结束时间', null=True)),
                ('owner_id', models.BigIntegerField(blank=True, db_comment='负责人ID', null=True)),
                ('owner_name', models.CharField(blank=True, db_comment='负责人姓名', max_length=50, null=True)),
                ('priority', models.PositiveIntegerField(db_comment='优先级(1: 高; 2: 中; 3: 低)', default=2)),
                ('status', models.PositiveIntegerField(db_comment='状态(1: 未开始; 2: 进行中; 3: 已完成; 4: 已取消)', default=1)),
                ('test_type', models.CharField(blank=True, db_comment='测试类型', max_length=50, null=True)),
                ('test_env', models.CharField(blank=True, db_comment='测试环境', max_length=50, null=True)),
                ('related_project', models.CharField(blank=True, db_comment='关联项目', max_length=100, null=True)),
                ('remark', models.TextField(blank=True, db_comment='备注', null=True)),
                ('create_user', models.BigIntegerField(db_comment='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_comment='创建时间')),
                ('update_user', models.BigIntegerField(blank=True, db_comment='修改人', null=True)),
                ('update_time', models.DateTimeField(auto_now=True, db_comment='修改时间', null=True)),
            ],
            options={
                'db_table': 'test_plan',
                'db_table_comment': '测试计划表',
            },
            bases=(xadmin_db.models.ModelSaveMixin, models.Model),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='is_active',
            field=models.BooleanField(db_comment='账号是否激活', default=True),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='is_staff',
            field=models.BooleanField(db_comment='是否可以访问admin', default=False),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
