# Generated by Django 5.2.7 on 2025-11-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SutDevice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=255, unique=True, verbose_name='设备主机名')),
                ('asic_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ASIC名称')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('device_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='设备ID')),
                ('rev_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='版本ID')),
                ('gpu_series', models.CharField(blank=True, max_length=100, null=True, verbose_name='GPU系列')),
                ('gpu_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='GPU型号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'SUT测试设备',
                'verbose_name_plural': 'SUT测试设备列表',
                'db_table': 'sut_devices',
                'ordering': ['hostname'],
                'managed': False,
            },
        ),
    ]
