# Generated by Django 5.2.7 on 2025-11-11 06:10

import django.db.models.deletion
import tpgen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestComponent',
            fields=[
                ('id', models.BigAutoField(db_comment='主键', primary_key=True, serialize=False)),
                ('component_category', models.CharField(blank=True, db_comment='组件分类（如 Media, Compute）', db_index=True, max_length=100, null=True)),
                ('component_name', models.CharField(db_comment='组件名称（如 ffmpeg, clpeak）', db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'test_components',
                'db_table_comment': '测试组件表',
            },
        ),
        migrations.CreateModel(
            name='OsConfig',
            fields=[
                ('id', models.BigAutoField(db_comment='主键', primary_key=True, serialize=False)),
                ('os_family', models.CharField(db_comment='操作系统家族（如 Ubuntu, RHEL）', db_index=True, max_length=100)),
                ('version', models.CharField(db_comment='操作系统版本', db_index=True, max_length=50)),
                ('download_url', models.CharField(blank=True, db_comment='镜像下载链接', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间')),
            ],
            options={
                'db_table': 'os_configs',
                'db_table_comment': '操作系统配置表',
                'indexes': [models.Index(fields=['os_family'], name='idx_os_configs_os_family'), models.Index(fields=['version'], name='idx_os_configs_version')],
                'unique_together': {('os_family', 'version')},
            },
            bases=(tpgen.models.ModelSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SutDevice',
            fields=[
                ('id', models.BigAutoField(db_comment='主键', primary_key=True, serialize=False)),
                ('hostname', models.CharField(db_comment='设备主机名（唯一）', max_length=255, unique=True)),
                ('asic_name', models.CharField(blank=True, db_comment='ASIC名称（如 Navi 31 GFX1100）', max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_comment='IP地址', db_index=True, null=True)),
                ('device_id', models.CharField(blank=True, db_comment='设备ID', max_length=50, null=True)),
                ('rev_id', models.CharField(blank=True, db_comment='版本ID', max_length=50, null=True)),
                ('gpu_series', models.CharField(blank=True, db_comment='GPU系列（如 Radeon RX 7000）', max_length=100, null=True)),
                ('gpu_model', models.CharField(blank=True, db_comment='GPU型号（如 RX 7900 XTX）', db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间')),
            ],
            options={
                'db_table': 'sut_devices',
                'db_table_comment': '测试设备表',
                'indexes': [models.Index(fields=['hostname'], name='idx_sut_devices_hostname'), models.Index(fields=['asic_name'], name='idx_sut_devices_asic_name'), models.Index(fields=['gpu_model'], name='idx_sut_devices_gpu_model')],
            },
            bases=(tpgen.models.ModelSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(db_comment='主键', primary_key=True, serialize=False)),
                ('case_name', models.CharField(db_comment='测试用例名称', db_index=True, max_length=255)),
                ('case_config', models.JSONField(blank=True, db_comment='测试用例配置（JSON格式）', default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间')),
                ('test_component', models.ForeignKey(db_comment='关联的测试组件ID', on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='tpgen.testcomponent')),
            ],
            options={
                'db_table': 'test_cases',
                'db_table_comment': '测试用例表',
            },
            bases=(tpgen.models.ModelSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.BigAutoField(db_comment='主键', primary_key=True, serialize=False)),
                ('plan_name', models.CharField(db_comment='测试计划名称', max_length=255)),
                ('plan_description', models.TextField(blank=True, db_comment='测试计划描述', null=True)),
                ('created_by', models.CharField(blank=True, db_comment='创建者', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间')),
                ('os_config', models.ForeignKey(db_comment='关联的操作系统配置ID', on_delete=django.db.models.deletion.RESTRICT, related_name='test_plans', to='tpgen.osconfig')),
                ('sut_device', models.ForeignKey(db_comment='关联的测试设备ID', on_delete=django.db.models.deletion.CASCADE, related_name='test_plans', to='tpgen.sutdevice')),
            ],
            options={
                'db_table': 'test_plans',
                'db_table_comment': '测试计划表',
            },
            bases=(tpgen.models.ModelSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TestPlanCase',
            fields=[
                ('id', models.BigAutoField(db_comment='主键', primary_key=True, serialize=False)),
                ('timeout', models.IntegerField(blank=True, db_comment='超时时长（秒）', null=True)),
                ('test_case', models.ForeignKey(db_comment='关联的测试用例ID', on_delete=django.db.models.deletion.CASCADE, related_name='plan_cases', to='tpgen.testcase')),
                ('test_plan', models.ForeignKey(db_comment='关联的测试计划ID', on_delete=django.db.models.deletion.CASCADE, related_name='plan_cases', to='tpgen.testplan')),
            ],
            options={
                'db_table': 'test_plan_cases',
                'db_table_comment': '测试计划与用例关联表',
            },
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(db_comment='主键', primary_key=True, serialize=False)),
                ('type_name', models.CharField(db_comment='测试类型名称', db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间')),
            ],
            options={
                'db_table': 'test_types',
                'db_table_comment': '测试类型表',
                'indexes': [models.Index(fields=['type_name'], name='idx_test_types_type_name')],
            },
            bases=(tpgen.models.ModelSaveMixin, models.Model),
        ),
        migrations.AddField(
            model_name='testcomponent',
            name='test_type',
            field=models.ForeignKey(db_comment='关联的测试类型ID', on_delete=django.db.models.deletion.CASCADE, related_name='components', to='tpgen.testtype'),
        ),
        migrations.CreateModel(
            name='OsSupportedKernel',
            fields=[
                ('id', models.BigAutoField(db_comment='主键', primary_key=True, serialize=False)),
                ('kernel_version', models.CharField(db_comment='内核版本号', db_index=True, max_length=100)),
                ('os_config', models.ForeignKey(db_comment='关联的操作系统配置ID', on_delete=django.db.models.deletion.CASCADE, related_name='supported_kernels', to='tpgen.osconfig')),
            ],
            options={
                'db_table': 'os_supported_kernels',
                'db_table_comment': '操作系统支持的内核版本表',
                'indexes': [models.Index(fields=['os_config'], name='idx_os_kernels_os_config'), models.Index(fields=['kernel_version'], name='idx_os_kernels_version')],
                'unique_together': {('os_config', 'kernel_version')},
            },
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['test_component'], name='idx_test_cases_component'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['case_name'], name='idx_test_cases_case_name'),
        ),
        migrations.AlterUniqueTogether(
            name='testcase',
            unique_together={('test_component', 'case_name')},
        ),
        migrations.AddIndex(
            model_name='testplan',
            index=models.Index(fields=['sut_device'], name='idx_test_plans_sut_device'),
        ),
        migrations.AddIndex(
            model_name='testplan',
            index=models.Index(fields=['os_config'], name='idx_test_plans_os_config'),
        ),
        migrations.AddIndex(
            model_name='testplancase',
            index=models.Index(fields=['test_plan'], name='idx_test_plan_cases_test_plan'),
        ),
        migrations.AddIndex(
            model_name='testplancase',
            index=models.Index(fields=['test_case'], name='idx_test_plan_cases_test_case'),
        ),
        migrations.AlterUniqueTogether(
            name='testplancase',
            unique_together={('test_plan', 'test_case')},
        ),
        migrations.AddIndex(
            model_name='testcomponent',
            index=models.Index(fields=['test_type'], name='idx_test_components_test_type'),
        ),
        migrations.AddIndex(
            model_name='testcomponent',
            index=models.Index(fields=['component_category'], name='idx_test_components_category'),
        ),
        migrations.AddIndex(
            model_name='testcomponent',
            index=models.Index(fields=['component_name'], name='idx_test_components_name'),
        ),
        migrations.AlterUniqueTogether(
            name='testcomponent',
            unique_together={('test_type', 'component_category', 'component_name')},
        ),
    ]
