# Generated by Django 5.2.7 on 2025-11-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpgen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sutdevice',
            name='product_name',
            field=models.CharField(blank=True, db_comment='产品系列名称（如 navi31, vangogh, mi300）', db_index=True, max_length=100, null=True),
        ),
    ]
