# Generated by Django 5.2.7 on 2025-11-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TpgenSavedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='测试计划名称')),
                ('category', models.CharField(max_length=100, verbose_name='类别')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('config_data', models.JSONField(help_text='前端配置表单数据', verbose_name='配置数据')),
                ('yaml_data', models.TextField(help_text='生成的YAML测试计划内容', verbose_name='YAML数据')),
                ('cpu', models.CharField(blank=True, max_length=100, null=True, verbose_name='CPU类型')),
                ('gpu', models.CharField(blank=True, max_length=100, null=True, verbose_name='GPU类型')),
                ('machine_count', models.IntegerField(default=1, verbose_name='机器数量')),
                ('os_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作系统类型')),
                ('kernel_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='内核类型')),
                ('test_case_count', models.IntegerField(default=0, verbose_name='测试用例数量')),
                ('status', models.IntegerField(default=1, help_text='0=草稿, 1=已发布, 2=已归档', verbose_name='状态')),
                ('tags', models.CharField(blank=True, help_text='多个标签用逗号分隔', max_length=255, null=True, verbose_name='标签')),
                ('use_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('last_used_time', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('create_user', models.IntegerField(verbose_name='创建人ID')),
                ('create_user_name', models.CharField(max_length=100, verbose_name='创建人名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(blank=True, null=True, verbose_name='更新人ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '保存的测试计划',
                'verbose_name_plural': '保存的测试计划',
                'db_table': 'tpgen_saved_plan',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['category'], name='tpgen_saved_categor_c4c5f8_idx'), models.Index(fields=['status'], name='tpgen_saved_status_f24714_idx'), models.Index(fields=['-create_time'], name='tpgen_saved_create__38a810_idx')],
            },
        ),
    ]
