# Generated by Django 5.2.7 on 2025-11-11 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xcase', '0002_migrate_content_types'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='casemetadata',
            new_name='case_metada_casespa_2e3c24_idx',
            old_name='case_metada_casesp_8b8e92_idx',
        ),
        migrations.RenameIndex(
            model_name='casemetadata',
            new_name='case_metada_create__e9de8d_idx',
            old_name='case_metada_create__3f3e5e_idx',
        ),
        migrations.RenameIndex(
            model_name='casemetadata',
            new_name='case_metada_update__962b9a_idx',
            old_name='case_metada_update__3ae091_idx',
        ),
        migrations.RenameIndex(
            model_name='caseoption',
            new_name='case_option_key_245e40_idx',
            old_name='case_option_key_9c7831_idx',
        ),
        migrations.RenameIndex(
            model_name='caseoption',
            new_name='case_option_metadat_c19484_idx',
            old_name='case_option_metadat_3e1ea7_idx',
        ),
        migrations.RenameIndex(
            model_name='casetag',
            new_name='case_tag_tag_566e26_idx',
            old_name='case_tag_tag_5c1f0f_idx',
        ),
        migrations.RenameIndex(
            model_name='casetag',
            new_name='case_tag_metadat_269d60_idx',
            old_name='case_tag_metadat_44f583_idx',
        ),
    ]
